### ISSUE TITLE
STUDENT STAKEHOLDER - Managing dates inside search proposal filter

### ISSUE THREAD

**Issue by PaoloCampagnaleS317687** [DanieleF36/SEII_Main-Project#4]
Inside the filter for the US Search Proposals there are the fields "expiration date" and "creation date" that act as a selector for the left end of a date range (the right is the current date). However, the graphical interface seems to suggest that these fields are used to report an exact date

**Comment by AngeloCiminos317631** [comment]
From Fixed

**Comment by AngeloCiminos317631** [comment]
Form Fixed
